version: '3'

services:
  web:
    build: 
      context: .
      restart: unless-stopped
      container_name: faceai
      volumes:
        - ./:/deliver
      ports:
        - 8001:8000
      command: bash -c "python amazon/main.py"
